import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - PandaLearn",
  description: "The terms and conditions governing your use of the PandaLearn platform.",
};

const SECTIONS = [
  {
    title: "Acceptance of Terms",
    body: "By accessing or using PandaLearn, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.",
  },
  {
    title: "Account Registration",
    body: "You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.",
  },
  {
    title: "Permitted Use",
    body: "PandaLearn is licensed for personal, non-commercial educational use. You may not reproduce, distribute, or create derivative works from our content without explicit written permission.",
  },
  {
    title: "AI Tutor Usage",
    body: "The AI tutor is provided for educational assistance. Responses are generated by AI and should not be treated as professional advice. We make no guarantees about the accuracy of AI-generated content.",
  },
  {
    title: "Subscriptions & Payments",
    body: "Pro subscriptions are billed monthly or annually via Razorpay. You may cancel at any time; cancellation takes effect at the end of the current billing cycle. Refunds are handled on a case-by-case basis - email us within 7 days of purchase.",
  },
  {
    title: "Intellectual Property",
    body: "All content on PandaLearn - including lessons, visualizations, illustrations, and code - is the intellectual property of PandaLearn. Your user-generated content (quiz answers, notes) remains yours.",
  },
  {
    title: "Termination",
    body: "We reserve the right to suspend or terminate accounts that violate these terms, engage in abuse, or attempt to reverse-engineer the platform.",
  },
  {
    title: "Limitation of Liability",
    body: "PandaLearn is provided 'as is'. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform.",
  },
  {
    title: "Governing Law",
    body: "These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in India.",
  },
];

export default function TermsOfService() {
  return (
    <>
      <Navbar />
      <main className="pt-28 pb-24 min-h-screen bg-white">
        <div className="mx-auto max-w-3xl px-6 lg:px-8">

          <nav className="text-sm text-gray-400 mb-8 flex items-center gap-1.5">
            <a href="/" className="hover:text-violet-600 transition-colors">Home</a>
            <span>/</span>
            <span className="text-gray-600">Terms of Service</span>
          </nav>

          <h1 className="font-sora text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-gray-400 text-sm mb-10">Last updated: May 2026 · Effective: May 2026</p>

          <div className="rounded-xl border border-amber-200 bg-amber-50 px-5 py-4 mb-12">
            <p className="text-amber-800 text-sm leading-relaxed">
              <strong>Beta notice:</strong> These terms are being reviewed with legal counsel ahead of our full public launch. The finalized version will be published before our official release.
            </p>
          </div>

          <p className="text-gray-600 text-base leading-relaxed mb-12">
            Please read these Terms of Service carefully before using PandaLearn. These terms constitute a legally binding agreement between you and PandaLearn.
          </p>

          <div className="space-y-10">
            {SECTIONS.map((s, i) => (
              <section key={s.title}>
                <h2 className="font-sora text-lg font-bold text-gray-900 mb-3 flex items-center gap-3">
                  <span className="w-7 h-7 rounded-lg bg-violet-100 text-violet-600 flex items-center justify-center text-xs font-bold shrink-0">
                    {i + 1}
                  </span>
                  {s.title}
                </h2>
                <p className="text-gray-600 text-sm leading-relaxed pl-10">{s.body}</p>
              </section>
            ))}
          </div>

          <div className="mt-14 pt-8 border-t border-gray-100">
            <p className="text-gray-500 text-sm">
              Questions about these terms? Contact us at{" "}
              <a href="mailto:hello@pandalearn.in" className="text-violet-600 hover:underline font-medium">
                hello@pandalearn.in
              </a>
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
